name: Verify Components - pnnl-dopf-admm

on:
  push:
    paths:
      - 'Components/pnnl-dopf-admm/**'
      - '.github/workflows/verify-components-pnnl-dopf-admm.yml'
      - '.github/workflows/reusable_verify_components.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_components.yml
    with:
      component-root: Components/pnnl-dopf-admm
