name: Verify Dockerfiles - LocalFeeder

on:
  workflow_dispatch:
  push:
    paths:
      - 'Components/LocalFeeder/**'
      - '.github/workflows/verify-dockerfiles-localfeeder.yml'
      - '.github/workflows/reusable_verify_dockerfiles.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_dockerfiles.yml
    with:
      component-root: Components/LocalFeeder
