name: Verify Components - pnnl-hub-control

on:
  workflow_dispatch:
  push:
    paths:
      - 'Components/pnnl-hub-control/**'
      - '.github/workflows/verify-components-pnnl-hub-control.yml'
      - '.github/workflows/reusable_verify_components.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_components.yml
    with:
      component-root: Components/pnnl-hub-control
