name: Verify Dockerfiles - lindistflow_federate

on:
  push:
    paths:
      - 'Components/lindistflow_federate/**'
      - '.github/workflows/verify-dockerfiles-lindistflow_federate.yml'
      - '.github/workflows/reusable_verify_dockerfiles.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_dockerfiles.yml
    with:
      component-root: Components/lindistflow_federate
