name: Verify Dockerfiles - pnnl-hub-voltage

on:
  workflow_dispatch:
  push:
    paths:
      - 'Components/pnnl-hub-voltage/**'
      - '.github/workflows/verify-dockerfiles-pnnl-hub-voltage.yml'
      - '.github/workflows/reusable_verify_dockerfiles.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_dockerfiles.yml
    with:
      component-root: Components/pnnl-hub-voltage
