name: Verify Dockerfiles

on:
  push:
    branches: [ main, al/restructed ]
    paths:
      - 'Components/**'
      - '.github/workflows/verify-dockerfiles.yml'
      - '.github/workflows/reusable_verify_dockerfiles.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Components/**'
      - '.github/workflows/verify-dockerfiles.yml'
      - '.github/workflows/reusable_verify_dockerfiles.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_dockerfiles.yml
