name: Verify Components - pnnl-dsse-ekf

on:
  push:
    paths:
      - 'Components/pnnl-dsse-ekf/**'
      - '.github/workflows/verify-components-pnnl-dsse-ekf.yml'
      - '.github/workflows/reusable_verify_components.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_components.yml
    with:
      component-root: Components/pnnl-dsse-ekf
