name: Verify Dockerfiles - pnnl-hub-power

on:
  push:
    paths:
      - 'Components/pnnl-hub-power/**'
      - '.github/workflows/verify-dockerfiles-pnnl-hub-power.yml'
      - '.github/workflows/reusable_verify_dockerfiles.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_dockerfiles.yml
    with:
      component-root: Components/pnnl-hub-power
