name: Verify Components - measuring_federate

on:
  workflow_dispatch:
  push:
    paths:
      - 'Components/measuring_federate/**'
      - '.github/workflows/verify-components-measuring_federate.yml'
      - '.github/workflows/reusable_verify_components.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_components.yml
    with:
      component-root: Components/measuring_federate
