name: Verify Dockerfiles - broker

on:
  workflow_dispatch:
  push:
    paths:
      - 'Components/broker/**'
      - '.github/workflows/verify-dockerfiles-broker.yml'
      - '.github/workflows/reusable_verify_dockerfiles.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_dockerfiles.yml
    with:
      component-root: Components/broker
