name: Verify Dockerfiles

on:
  push:
    paths:
      - 'Components/**'
      - '.github/workflows/verify-dockerfiles.yml'
      - '.github/workflows/reusable_verify_dockerfiles.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_dockerfiles.yml
