name: Verify Components

on:
  push:
    branches: [ main, al/restructed ]
    paths:
      - 'Components/**'
      - '.github/workflows/verify-components.yml'
      - '.github/workflows/reusable_verify_components.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Components/**'
      - '.github/workflows/verify-components.yml'
      - '.github/workflows/reusable_verify_components.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_components.yml
