name: Verify Dockerfiles - wls_federate

on:
  workflow_dispatch:
  push:
    paths:
      - 'Components/wls_federate/**'
      - '.github/workflows/verify-dockerfiles-wls_federate.yml'
      - '.github/workflows/reusable_verify_dockerfiles.yml'

jobs:
  verify:
    uses: ./.github/workflows/reusable_verify_dockerfiles.yml
    with:
      component-root: Components/wls_federate
